[[install-config-install-host-preparation]]
= Preparing your hosts
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:
include::_snippets/glusterfs.adoc[]

toc::[]

在安装{product-title}之前，必须准备节点主机。它们必须满足以下要求。

ifdef::openshift-enterprise[]

[[software-prerequisites]]
== 操作系统需求

主主机和节点主机必须使用Red Hat Enterprise Linux (RHEL) 7.4或更高版本的基础安装，
以及Extras通道或RHEL原子主机7.4.2或更高版本的最新包。如有需要，请参阅以下有关安装指引的文件:

- https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/index.html[Red Hat Enterprise Linux 7 Installation Guide]
- https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/installation-and-configuration-guide/[Red Hat Enterprise Linux Atomic Host 7 Installation and Configuration Guide]

endif::[]

[[setting-path]]
== 设置路径

每个主机上的根用户的`路径`必须包含以下目录:

- *_/bin_*
- *_/sbin_*
- *_/usr/bin_*
- *_/usr/sbin_*

这些目录在新的RHEL 7.x默认安装。

[[ensuring-host-access]]
== 确保主机访问

{product-title}安装程序需要一个可以访问所有主机的用户。如果你想以非root用户的身份运行安装程序，
首先配置无密码的*sudo*权限给每台主机:

. 在运行安装剧本的主机上生成SSH密钥:
+
----
# ssh-keygen
----
+
*不要*使用密码。

. 将密钥分发给其他集群主机。你可以使用一个' bash '循环:
+
----
# for host in master.example.com \ <1>
    node1.example.com \  <1>
    node2.example.com; \ <1>
    do ssh-copy-id -i ~/.ssh/id_rsa.pub $host; \
    done
----
<1> 为每个集群主机提供主机名。

. 确认您可以通过SSH访问循环中列出的每个主机。

[[setting-proxy-overrides]]
== 设置代理覆盖

如果节点上的*_/etc/environment_*文件包含`http_proxy`或`https_proxy`值，
则必须在该文件中设置`no_proxy`值，以允许{product-title}组件之间打开通信。

[NOTE]
====
*_/etc/environment_*文件中的`no_proxy`参数与您在目录文件中设置的全局代理值不同。
全局代理值使用代理设置配置特定的{product-title}服务。
更多详细信息，请查看
xref:configuring_inventory_file.adoc#advanced-install-configuring-global-proxy[配置全局代理选项]。
====

如果*_/etc/environment_*文件包含代理值，则在每个节点上该文件的`no_proxy`参数中定义以下值:

* 主主机名和节点主机名或它们的域后缀。
* 其他内部主机名或其域后缀。
* Etcd IP地址。您必须提供IP地址而不是主机名，因为*etcd*访问由IP地址控制。
* Kubernetes的IP地址，默认为`172.30.0.1`。必须设置的值
xref:configuring_inventory_file.adoc#advanced-install-networking-variables-table[`openshift_portal_net`]目录文件中的参数。
* 内部域名后缀 `cluster.local`。
* 内部域名后缀，`.svc`.

[NOTE]
====
因为`no_proxy`不支持CIDR, 所以可以使用域后缀。
====

如果您使用`http_proxy`或`https_proxy`值，您的`no_proxy`参数值类似于以下示例：

----
no_proxy=.internal.example.com,10.0.0.1,10.0.0.2,10.0.0.3,.cluster.local,.svc,localhost,127.0.0.1,172.30.0.1
----

ifdef::openshift-enterprise[]

[[host-registration]]
== 注册主机

要访问安装包，必须向Red Hat Subscription Manager (RHSM)注册每个主机，并附加一个活动的{product-title}订阅。

. 在每个主机上，注册RHSM:
+
----
# subscription-manager register --username=<user_name> --password=<password>
----

. 从RHSM获取最新订阅数据:
+
----
# subscription-manager refresh
----

. List the available subscriptions:
+
----
# subscription-manager list --available --matches '*OpenShift*'
----

. 在前一个命令的输出中，找到一个{product-title}订阅的池ID，并将其附加:
+
----
# subscription-manager attach --pool=<pool_id>
----

. 禁用所有yum存储库:
.. 禁用所有启用的RHSM存储库:
+
----
# subscription-manager repos --disable="*"
----

.. 列出剩余的yum存储库，并在`repo id`下记下它们的名称, 如果有的话:
+
----
# yum repolist
----

.. 使用`yum-config-manager`禁用剩余的yum存储库:
+
----
# yum-config-manager --disable <repo_id>
----
+
Alternatively, disable all repositories:
+
----
 yum-config-manager --disable \*
----
+
注意，如果您有大量可用的存储库，这可能需要几分钟

. 只启用{product-title} 3.11所需的存储库:
+
----
# subscription-manager repos \
    --enable="rhel-7-server-rpms" \
    --enable="rhel-7-server-extras-rpms" \
    --enable="rhel-7-server-ose-3.11-rpms" \
    --enable="rhel-7-server-ansible-2.6-rpms"
----
endif::[]

[[installing-base-packages]]
== 安装基础包

[IMPORTANT]
====
如果您的主机使用RHEL 7.5，并且您希望接受{product-title}的默认*docker*
配置(使用OverlayFS存储和所有默认日志选项)，
则不需要手动安装这些包。这些包是在运行*prerequisites.yml*期间安装
xref:running_install.adoc#running-the-installation-playbooks[安装]。

如果您的主机使用RHEL 7.4或RHEL 7.5，并且您想定制*docker*配置，请安装这些包。
====

.RHEL 7系统:

. 安装以下基本软件包:
+
----
# yum install wget git net-tools bind-utils yum-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct
----

. 更新系统到最新的软件包:
+
----
# yum update
# reboot
----


. 安装方法所需的安装包:
** 如果你打算用
xref:running_install.adoc#running-the-advanced-installation-system-container[容器化安装程序],
安装以下软件包：
+
----
# yum install atomic
----

ifdef::openshift-enterprise[]
** 如果你打算用
xref:running_install.adoc#running-the-advanced-installation-rpm[基于RPM的安装程序],
安装以下软件包：
+
----
# yum install openshift-ansible
----
+
这个包提供安装程序实用程序，并引入集群安装过程需要的其他包，
如Ansible、playbook和相关配置文件
endif::[]
ifdef::openshift-origin[]
** 如果你准备使用
xref:running_install.adoc#running-the-advanced-installation-rpm[基于RPM的安装程序]:

.. 安装Ansible。使用EPEL作为Ansible的包源:

... 安装EPEL存储库:
+
----
# yum -y install \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
----

... 全局禁用EPEL存储库，以便在安装的后续步骤中不会意外使用:
+
----
# sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
----

... 安装Ansible的软件包:
+
----
# yum -y --enablerepo=epel install ansible pyOpenSSL
----

.. 从GitHub克隆*openshift/openshift-ansible*，它提供了所需的剧本和配置文件：
+
----
# cd ~
# git clone https://github.com/openshift/openshift-ansible
# cd openshift-ansible
# git checkout release-3.11
----
+
[NOTE]
====
确保使用*openshift-ansible*的发布分支，它对应于您的{product-title}版本。
使用*master*分支在开发中安装{product-title}版本。
====
endif::[]

.RHEL 7原子主机系统:

. 如果有最新的原子树，请升级到最新的原子树，以确保主机是最新的:
+
----
# 原子主机升级
----

. 升级完成并为下一次引导做好准备后，重启主机:
+
----
# 重启
----

[[installing-docker]]
== 安装Docker

此时，在所有主主机和节点主机上安装Docker。
这允许您在安装{product-title}之前配置您的xref:configuring-docker-storage[Docker存储选项]。

[NOTE]
====
集群安装过程自动修改*_/etc/sysconfig/docker_*文件。
====

.RHEL 7系统:

. 安装Docker 1.13:
+
----
# yum install docker-1.13.1
----

. 验证版本1.13是否已安装:
+
----
# rpm -V docker-1.13.1
# docker version
----

.对于RHEL 7原子主机系统:
不需要任何操作。默认情况下安装、配置和运行Docker。

[[configuring-docker-storage]]
== Docker配置存储

容器及其创建的映像存储在Docker的存储后端。这个存储是临时的，与任何
xref:../install_config/persistent_storage/index.adoc#install-config-persistent-storage-index[persistent
storage]分配以满足您的应用程序的需要。使用 _临时存储_,
当容器被删除时，容器保存的数据将丢失。使用
_持久存储_, 如果容器被删除，容器保存的数据将保留下来。

必须为所有主主机和节点主机配置存储，因为默认情况下每个系统运行一个容器守护进程。
对于容器化安装，您需要在主服务器上存储。另外，默认情况下，
Web控制台和etcd(需要存储)在主机上的容器中运行。容器在节点上运行，因此总是需要在节点上存储。

存储的大小取决于工作负载、容器的数量、正在运行的容器的大小以及容器的存储需求。

[IMPORTANT]
====
如果您的主机使用RHEL 7.5，并且希望接受{product-title}的默认*docker*配置
(使用OverlayFS存储和所有默认日志选项)，
则不需要手动安装这些包，这些包是在运行*prerequisites.yml*先前安装的。
xref:running_install.adoc#running-the-installation-playbooks[安装]。

如果您的主机使用RHEL 7.4或RHEL 7.5，并且您想定制*docker*配置，
请安装这些包。
====

.对于RHEL 7体系:

RHEL 7上Docker的默认存储后端是环回设备上的一个瘦池，它不支持生产使用，只适合证明概念环境。
对于生产环境，您必须创建一个瘦池逻辑卷，并重新配置Docker以使用该卷。

Docker在图形驱动程序中存储图像和容器，这是一种可插入的存储技术，例如*DeviceMapper*,
*OverlayFS*, 和 *Btrfs*。每种方法都有优点和缺点。例如，在启动和停止容器时，OverlayFS比DeviceMapper更快，
但由于union文件系统的体系结构限制，它不是兼容Unix(POSIX)的可移植操作系统接口。参见链接:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/?version=7[Red Hat Enterprise Linux]
发布关于在RHEL版本中使用OverlayFS的信息。

有关DeviceMapper和OverlayFS的优点和限制的更多信息，请参见
see xref:../scaling_performance/optimizing_storage.adoc#choosing-a-graph-driver[选择一个图形驱动程序]。

.RHEL 7原子主机系统:

RHEL原子主机上Docker的默认存储后端是一个瘦池逻辑卷，它支持生产环境。
您必须确保根据xref:prerequisites.adoc#system-requirements[系统需求]中提到的Docker存储需求为这个卷分配了足够的空间需求。

如果没有分配足够的空间，请参见链接:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/managing_containers/#managing_storage_with_docker_formatted_containers[使用Docker格式的容器管理存储]
了解有关使用*docker-storage-setup*和RHEL原子主机中存储管理的基本说明。


[[configuring-docker-overlayfs]]
=== 配置OverlayFS

OverlayFS是联合文件系统的一种类型。它允许您将一个文件系统覆盖在另一个文件系统之上。
更改记录在上层文件系统中，而下层文件系统保持不变。

xref:../scaling_performance/optimizing_storage.adoc#comparing-overlay-graph-drivers[比较覆盖图驱动程序]
有关*覆盖*和*覆盖2*驱动程序的更多信息。

有关为Docker服务启用OverlayFS存储驱动程序的信息，请参见
link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/managing_containers/#using_the_overlay_graph_driver[Red Hat Enterprise Linux原子主机文档]。


[[configuring-docker-thin-pool]]
=== 配置瘦池存储

您可以使用Docker中包含的*docker-storage-setup*脚本创建一个瘦池设备并配置Docker的存储驱动程序。
您可以在安装Docker之后这样做，并且必须在创建映像或容器之前这样做。
脚本从*_/etc/sysconfig/docker-storage-setup_*文件中读取配置选项，并支持创建逻辑卷的三个选项:

- 使用额外的块设备。
- 使用现有的指定卷组。
- 使用根文件系统所在卷组中的剩余空闲空间。

使用额外的块设备是最健壮的选项，但它要求在配置Docker存储之前向主机添加另一个块设备。
其他选项都要求在提供主机时留出空闲空间。使用根文件系统卷组中剩余的空闲空间会导致
某些应用程序出现问题，例如Red Hat Mobile Application Platform (RHMAP)。

. 使用以下三个选项之一创建*docker-pool*卷:

** 要使用额外的块设备:
.. *_/etc/sysconfig/docker-storage-setup_*, 将*DEVS*设置为要使用的块设备的路径。
将*VG*设置为要创建的卷组名称，例如*docker-vg*。例如:
+
----
# cat <<EOF > /etc/sysconfig/docker-storage-setup
DEVS=/dev/vdc
VG=docker-vg
EOF
----
.. 运行*docker-storage-setup*并检查输出，确保创建了*docker-pool*卷:
+
----
# docker-storage-setup                                                                                                                                                                                                                                [5/1868]
0
检查是否有人正在使用这个磁盘 ...
OK

Disk /dev/vdc: 31207 cylinders, 16 heads, 63 sectors/track
sfdisk:  /dev/vdc: unrecognized partition table type

Old situation:
sfdisk: No partitions found

New situation:
Units: sectors of 512 bytes, counting from 0

   Device Boot    Start       End   #sectors  Id  System
/dev/vdc1          2048  31457279   31455232  8e  Linux LVM
/dev/vdc2             0         -          0   0  Empty
/dev/vdc3             0         -          0   0  Empty
/dev/vdc4             0         -          0   0  Empty
Warning: partition 1 does not start at a cylinder boundary
Warning: partition 1 does not end at a cylinder boundary
Warning: no primary partition is marked bootable (active)
这对LILO来说无关紧要，但是DOS MBR不会引导这个磁盘。成功地编写了新的分区表

重新读取分区表 ...

如果您创建或更改了一个DOS分区， /dev/foo7, say, 那么使用dd(1)
将前512字节变为零:  dd if=/dev/zero of=/dev/foo7 bs=512 count=1
(See fdisk(8).)
  成功创建物理卷"/dev/vdc1"。
  成功创建卷组"docker-vg"
  四舍五入大小到整个物理范围16.00 MiB
  创建逻辑卷"docker-poolmeta"。
  创建逻辑卷"docker-pool"。
  警告: 将逻辑卷docker-vg/docker-pool和docker-vg/docker-poolmeta转换为池的数据和元数据卷。
  这将破坏逻辑卷(文件系统等)的内容。
  将docker-vg/docker-pool转换为瘦池。
  逻辑卷"docker-pool"更改。
----

** 若要使用现有的指定卷组，请:
.. 在*_/etc/sysconfig/docker-storage-setup_*中，将*VG*设置为卷组，例如：
+
----
# cat <<EOF > /etc/sysconfig/docker-storage-setup
VG=docker-vg
EOF
----
.. 然后运行*docker-storage-setup*，检查输出，确保创建了*docker-pool*卷:
+
----
# docker-存储-设置
  四舍五入大小到整个物理范围16.00 MiB
  创建逻辑卷"docker-poolmeta"。
  创建逻辑卷"docker-pool"。
  警告: 将逻辑卷docker-vg/docker-pool和docker-vg/docker-poolmeta转换为池的数据和元数据卷。
  这将破坏逻辑卷(文件系统等)的内容。
  将docker-vg/docker-pool转换为瘦池。
  逻辑卷"docker-pool"更改。
----

** 要使用根文件系统所在卷组的剩余空闲空间:
.. 验证根文件系统所在的卷组具有所需的空闲空间，然后运行*docker-storage-setup*并检查输出，确保创建了*docker-pool*卷:
+
----
# docker-storage-setup
  四舍五入大小到整个物理范围32.00 MiB
  创建逻辑卷"docker-poolmeta"。
  创建逻辑卷"docker-pool"。
  警告:将逻辑卷rhel/docker-pool和rhel/docker-poolmeta转换为池的数据和元数据卷。
  这将破坏逻辑卷(文件系统等)的内容。
  将rhel/docker-pool转换为瘦池。
  逻辑卷"docker-pool"更改。
----

. 验证您的配置。确认*_/etc/sysconfig/docker-storage_*文件具有
*dm.thinpooldev*和*docker-pool*逻辑卷值：
+
----
# cat /etc/sysconfig/docker-storage
DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/rhel-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true "

# lvs
  LV          VG   Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool rhel twi-a-t---  9.29g             0.00   0.12
----
+
[IMPORTANT]
====
在使用Docker或{product-title}之前，请验证*docker-pool*逻辑卷是否足够大以满足您的需求。
使*docker-pool*卷占可用卷组的60%，它将通过LVM监视填充卷组。
====

. 启动或重启Docker.
** 如果Docker从未在主机上运行过，启用并启动服务，然后验证它正在运行:
+
----
# systemctl enable docker
# systemctl start docker
# systemctl is-active docker
----
** If Docker is already running:
.. Re-initialize Docker:
+
[WARNING]
====
这将破坏当前主机上的任何容器或映像。
====
+
----
# systemctl stop docker
# rm -rf /var/lib/docker/*
# systemctl restart docker
----
.. 删除*_/var/lib/docker/_*文件夹中的任何内容。

[[reconfiguring-docker-storage]]
=== 重新配置Docker存储

如果创建*docker-pool*后需要重新配置Docker存储:

. 删除*docker-pool*逻辑卷。

. 如果使用专用卷组，请删除卷组和任何关联的物理卷

. 再次运行*docker-storage-setup*。

请查看
link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Logical_Volume_Manager_Administration/index.html[逻辑卷管理器管理]
有关LVM管理的更详细信息。

[[enabling-image-signature-support]]
=== 启用图像签名支持

{product-title}能够加密验证图像来自可信源。
xref:../security/deployment.adoc#security-deployment-from-where-images-deployed[容器安全指南]
提供了对映像签名工作原理的高级描述。

您可以使用1.12.5或更高版本的`原子`命令行接口(CLI)配置图像签名验证。
ifdef::openshift-enterprise[]
`原子`的CLI预先安装在RHEL原子主机系统上。

[NOTE]
====
有关`原子` CLI的更多信息，请参见链接:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/cli_reference/prerequisites[原子CLI文档].
====
endif::[]

以下文件和目录组成主机的信任配置:

- *_/etc/containers/registries.d/*_*
- *_/etc/containers/policy.json_*

例如，您可以直接管理每个节点上的信任配置，或者管理单独主机上的文件，
使用Ansible将这些文件分发到适当的节点。查看链接:
https://access.redhat.com/articles/2750891#automating-cluster-configuration
[容器映像签名集成指南]了解使用Ansible自动化文件分发的示例。

. 安装*原子*包，如果它没有安装在主机系统：
+
----
$ yum install atomic
----

. 查看当前信任配置:
+
----
$ atomic trust show
* (default)                         accept
----
+
默认配置是将所有注册中心白名单，这意味着没有配置任何签名验证。

. 自定义信任配置。在下面的示例中，您将一个注册表或名称空间、
黑名单(拒绝)不受信任的注册表列入白名单，并要求对供应商注册表进行签名验证:
+
----
$ atomic trust add --type insecureAcceptAnything 172.30.1.1:5000

$ atomic trust add --sigstoretype atomic \
  --pubkeys pub@example.com \
  172.30.1.1:5000/production

$ atomic trust add --sigstoretype atomic \
  --pubkeys /etc/pki/example.com.pub \
  172.30.1.1:5000/production

$ atomic trust add --sigstoretype web \
  --sigstore https://access.redhat.com/webassets/docker/content/sigstore \
  --pubkeys /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release \
  registry.redhat.io

# atomic trust show
* (default)                         accept
172.30.1.1:5000                     accept
172.30.1.1:5000/production          signed security@example.com
registry.redhat.io                  signed security@redhat.com,security@redhat.com
----

. 您可以通过添加全局`拒绝`默认信任来进一步加固节点:
+
----
$ atomic trust default reject

$ atomic trust show
* (default)                         reject
172.30.1.1:5000                     accept
172.30.1.1:5000/production          signed security@example.com
registry.redhat.io                  signed security@redhat.com,security@redhat.com
----

. 可以通过查看`原子`手册页`man atomic-trust`以获得更多配置选项。

[[managing-docker-container-logs]]
=== 容器管理日志

为了防止容器的日志文件，
*_/var/lib/docker/containers/<hash>/<hash>-json.log_* 在容器运行的节点上，
从增加到有问题的大小，您可以配置Docker的`json-file`日志驱动程序来限制日志文件的大小和数量。

[options="header"]
|===

|选项 |目的

|`--log-opt max-size`
|设置创建新日志文件的大小。

|`--log-opt max-file`
|设置每个主机要保存的日志文件的最大数量。
|===

. 要配置日志文件，请编辑*_/etc/sysconfig/docker_*文件。例如，要将最大文件大小设置为
1MB，并始终保留最后三个日志文件，请在`OPTIONS=`行中添加`max-size=1M`和`max-file=3`，
确保值保持单引号格式：
+
----
OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled --log-opt max-size=1M --log-opt max-file=3'
----
+
有关如何链接的更多信息，请参见Docker的文档：
https://docs.docker.com/engine/admin/logging/overview/#/options[配置日志驱动程序]。

. 重启Docker服务:
+
----
# systemctl restart docker
----

[[viewing-available-container-logs]]
=== 查看可用的容器日志

您可以在容器运行的节点上的*_/var/lib/docker/containers/<hash>/_*目录中查看容器日志。例如：
----
# ls -lh /var/lib/docker/containers/f088349cceac173305d3e2c2e4790051799efe363842fdab5732f51f5b001fd8/
total 2.6M
-rw-r--r--. 1 root root 5.6K Nov 24 00:12 config.json
-rw-r--r--. 1 root root 649K Nov 24 00:15 f088349cceac173305d3e2c2e4790051799efe363842fdab5732f51f5b001fd8-json.log
-rw-r--r--. 1 root root 977K Nov 24 00:15 f088349cceac173305d3e2c2e4790051799efe363842fdab5732f51f5b001fd8-json.log.1
-rw-r--r--. 1 root root 977K Nov 24 00:15 f088349cceac173305d3e2c2e4790051799efe363842fdab5732f51f5b001fd8-json.log.2
-rw-r--r--. 1 root root 1.3K Nov 24 00:12 hostconfig.json
drwx------. 2 root root    6 Nov 24 00:12 secrets
----

[[blocking-local-volume-usage]]
=== 阻塞本地卷使用

当使用*_Dockerfile_*中的`VOLUME`指令或使用`docker run -v <volumename>`
命令供应商时，将使用主机的存储空间。使用此存储可能导致意外的空间不足问题，
并可能导致主机宕机。

在{product-title}中，试图运行自己的映像的用户可能会占用节点主机上的整个存储空间。
这个问题的一个解决方案是防止用户运行带有卷的图像。这样，用户只能访问有限的存储，
集群管理员可以分配存储配额。

使用*docker-novolume-plugin*通过禁止使用定义了本地卷的容器来解决这个问题。
特别是，插件块`docker run`命令包括：

- The `--volumes-from` option
- 定义了`VOLUME`(s)的图像
- 对`docker volume`提供现有卷的引用命令

该插件不会阻塞绑定挂载的引用。

要启用*docker-novolume-plugin*，请在每个节点主机上执行以下步骤：

. Install the *docker-novolume-plugin* package:
+
----
$ yum install docker-novolume-plugin
----

. 启用并启动*docker-novolume-plugin*服务:
+
----
$ systemctl enable docker-novolume-plugin
$ systemctl start docker-novolume-plugin
----

. 编辑*_/etc/sysconfig/docker_*文件，并在`选项`列表中添加以下内容:
+
----
--authorization-plugin=docker-novolume-plugin
----

. 重启*docker*服务:
+
----
$ systemctl restart docker
----

启用此插件后，定义了本地卷的容器无法启动，并显示以下错误消息:

----
runContainer: API error (500): authorization denied by plugin
docker-novolume-plugin: volumes are not allowed
----

[[prereq-glusterfs]]
== {gluster}软件需求

包括::install_config/persistent_storage/topics/glusterfs_prereqs_software.adoc[]

[[host-prep-whats-next]]
== 下一个步骤

ifdef::openshift-enterprise[]
在您准备好主机之后，如果您正在安装{product-title}，
xref:configuring_inventory_file.adoc#configuring-ansible[配置你的库存文件]。
如果正在安装独立注册表，请继续
xref:stand_alone_registry.adoc#install-config-installing-stand-alone-registry[安装独立注册表].
endif::[]

ifdef::openshift-origin[]
如果您是从
xref:../getting_started/administrators.adoc#getting-started-administrators[管理员入门],
您现在可以继续选择
xref:../getting_started/administrators.adoc#installation-methods[安装方法]. 
或者，您也可以使用标准集群安装过程安装{product-title}，
方法是继续安装到xref:configuring_inventory_file.adoc#configuring-ansible[配置您的库存文件].
endif::[]
